USE abundance_db;

INSERT INTO products (item_name, photo_url, category)
VALUES	('apple', 'apple.jpg', 'fruit'),
		('avocado','avocado.jpg', 'fruit'),
		('blackberry','blackberry.jpg', 'fruit'),
		('blueberry','blueberry.jpg', 'fruit'),
		('grape','grape.jpg', 'fruit'),
		('lemon','lemon.jpg', 'fruit'),
		('lime','lime.jpg', 'fruit'),
		('orange','orange.jpg', 'fruit'),
		('strawberry','strawberry.jpg', 'fruit'),
		('tomato','tomato.jpg', 'fruit'),
		('basil','basil.jpg', 'herb'),
		('chive','chive.jpg', 'herb'),
		('dill','dill.jpg', 'herb'),
		('ginger','ginger.jpg', 'herb'),
		('lavender','lavender.jpg', 'herb'),
		('mint','mint.jpg', 'herb'),
		('oregano','oregano.jpg', 'herb'),
		('parsley','parsley.jpg', 'herb'),
		('rosemary','rosemary.jpg', 'herb'),
		('thyme','thyme.jpg', 'herb'),
		('broccoli','broccoli.jpg', 'vegatable'),
		('carrot','carrot.jpg', 'vegatable'),
		('cucumber','cucumber.jpg', 'vegatable'),
		('eggplant','eggplant.jpg', 'vegatable'),
		('garlic','garlic.jpg', 'vegatable'),
		('kale','kale.jpg', 'vegatable'),
		('lettuce','lettuce.jpg', 'vegatable'),
		('onion','onion.jpg', 'vegatable'),
		('potato','potato.jpg', 'vegatable'),
		('spinach','spinach.jpg', 'vegatable');
